services:
  api:
    build: .
    container_name: cdcat-server

    ports:
      - "8080:8080"


    restart: unless-stopped

  postgres:
    image: postgres:18.2
    environment:
      POSTGRES_DB: "cdcat-pg"
      POSTGRES_USER: "whitekotan"
      POSTGRES_PASSWORD: "password123"
  
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  
    ports:
      - "5432:5432"

    restart: unless-stopped

volumes:
  data: